publication_top_name: "Medicines Used in Mental Health"
publication_sub_name: "England October to December 2023"
publication_table_title: "Medicines Used in Mental Health - England - April 2015 to December 2023"
cover_sheet_sub_title: "England Quarterly Summary Statistics April 2015 to December 2023"
publication_date: "7 March 2024"

publication_0403_name: "Medicines Used in Mental Health - <br> Antidepressant drugs"
publication_0401_name: "Medicines Used in Mental Health - <br> Hypnotics and anxiolytics"
publication_0402_name: "Medicines Used in Mental Health - <br> Drugs used in psychoses and related disorders"
publication_0404_name: "Medicines Used in Mental Health - <br> Central nervous system (CNS) stimulants and drugs used for ADHD"
publication_0411_name: "Medicines Used in Mental Health - <br> Drugs for dementia"
publication_model_name: "Medicines Used in Mental Health -  <br> Prescribing during the COVID-19 pandemic"

responsible_statistician: ""
sql_table_name: ""

html_top_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_quarterly_dec23_overview.html"
html_0401_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_quarterly_dec23_0401.html"
html_0402_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_quarterly_dec23_0402.html"
html_0403_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_quarterly_dec23_0403.html"
html_0404_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_quarterly_dec23_0404.html"
html_0411_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_quarterly_dec23_0411.html"
html_model_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_quarterly_dec23_model.html"

quart_0401_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0401_Dec_23.xlsx"
quart_0402_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0402_Dec_23.xlsx"
quart_0403_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0403_Dec_23.xlsx"
quart_0404_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0404_Dec_23.xlsx"
quart_0411_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0411_Dec_23.xlsx"

background_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_background_dec23.html"
stats_survey_link: "https://online1.snapsurveys.com/Official_Statistics_Feedback"
