publication_top_name: "Medicines Used in Mental Health"
publication_sub_name: "England July to September 2023"
publication_table_title: "Medicines Used in Mental Health - England - April 2015 to September 2023"
cover_sheet_sub_title: "England Quarterly Summary Statistics April 2015 to September 2023"
publication_date: "7 December 2023"

publication_0403_name: "Medicines Used in Mental Health - <br> Antidepressant drugs"
publication_0401_name: "Medicines Used in Mental Health - <br> Hypnotics and anxiolytics"
publication_0402_name: "Medicines Used in Mental Health - <br> Drugs used in psychoses and related disorders"
publication_0404_name: "Medicines Used in Mental Health - <br> Central nervous system (CNS) stimulants and drugs used for ADHD"
publication_0411_name: "Medicines Used in Mental Health - <br> Drugs for dementia"
publication_model_name: "Medicines Used in Mental Health -  <br> Prescribing during the COVID-19 pandemic"

responsible_statistician: ""
sql_table_name: ""

html_top_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_quarterly_sep23_overview.html"
html_0401_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_quarterly_sep23_0401.html"
html_0402_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_quarterly_sep23_0402.html"
html_0403_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_quarterly_sep23_0403.html"
html_0404_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_quarterly_sep23_0404.html"
html_0411_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_quarterly_sep23_0411.html"
html_model_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_quarterly_sep23_model.html"

quart_0401_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0401_Sep_23.xlsx"
quart_0402_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0402_Sep_23.xlsx"
quart_0403_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0403_Sep_23.xlsx"
quart_0404_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0404_Sep_23.xlsx"
quart_0411_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0411_Sep_23.xlsx"

background_link: ""
stats_survey_link: "https://online1.snapsurveys.com/Official_Statistics_Feedback"
