publication_top_name: "Medicines Used in Mental Health"
publication_0403_name: "Medicines Used in Mental Health - <br> Antidepressant drugs"
publication_0401_name: "Medicines Used in Mental Health - <br> Hypnotics and anxiolytics"
publication_0402_name: "Medicines Used in Mental Health - <br> Drugs used in psychoses and related disorders"
publication_0404_name: "Medicines Used in Mental Health - <br> Central nervous system (CNS) stimulants and drugs used for ADHD"
publication_0411_name: "Medicines Used in Mental Health - <br> Drugs for dementia"
publication_model_name: "Medicines Used in Mental Health -  <br> Prescribing during the COVID-19 pandemic"
publication_sub_name: "England April to June 2023"
publication_date: "14 September 2023"
responsible_statistician: "Kirsty Gray"
html_top_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_quarterly_jun23_overview.html"
html_0401_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_quarterly_jun23_0401.html"
html_0402_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_quarterly_jun23_0402.html"
html_0403_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_quarterly_jun23_0403.html"
html_0404_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_quarterly_jun23_0404.html"
html_0411_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_quarterly_jun23_0411.html"
html_model_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_quarterly_jun23_model.html"

fy_0401_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0401_2022_23.xlsx"
fy_0402_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0402_2022_23.xlsx"
fy_0403_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0403_2022_23.xlsx"
fy_0404_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0404_2022_23.xlsx"
fy_0411_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0411_2022_23.xlsx"
quart_0401_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0401_Jun_23.xlsx"
quart_0402_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0402_Jun_23.xlsx"
quart_0403_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0403_Jun_23.xlsx"
quart_0404_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0404_Jun_23.xlsx"
quart_0411_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0411_Jun_23.xlsx"
background_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/MUMH_Background_Info_Methodology_v009.html"
stats_survey_link: "https://online1.snapsurveys.com/Official_Statistics_Feedback"
