publication_name: "Medicines Used in Mental Health"
publication_sub_name: "England 2022/23 and January to March 2023"
publication_date: "6 July 2023"
responsible_statistician: "Grace Libby"
fy_0401_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0401_2022_23.xlsx"
fy_0402_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0402_2022_23.xlsx"
fy_0403_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0403_2022_23.xlsx"
fy_0404_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0404_2022_23.xlsx"
fy_0411_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0411_2022_23.xlsx"
quart_0401_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0401_Mar_23.xlsx"
quart_0402_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0402_Mar_23.xlsx"
quart_0403_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0403_Mar_23.xlsx"
quart_0404_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0404_Mar_23.xlsx"
quart_0411_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/mumh_bnf0411_Mar_23.xlsx"
background_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/mumh/MUMH_Background_Info_Methodology_v008.html"
stats_survey_link: "https://online1.snapsurveys.com/Official_Statistics_Feedback"