publication_name: "Medicines Used in Mental Health"
publication_sub_name: "England 2022/23 and January to March 2023"
publication_date: "6 July 2023"
responsible_statistician: "Grace Libby"
fy_0401_link: 
fy_0402_link:
fy_0403_link:
fy_0404_link:
fy_0411_link:
quart_0401_link:
quart_0402_link:
quart_0403_link:
quart_0404_link:
quart_0411_link:
background_link: 
stats_survey_link: "https://online1.snapsurveys.com/Official_Statistics_Feedback"